packages:
  - packages/*
  - scripts/*
  - website
catalogs:
  tailwindcss3:
    tailwindcss: ^3.4.17
    tailwindcss-3: npm:tailwindcss@^3.4.17
  tailwindcss4:
    tailwindcss: ^4.1.12
    tailwindcss-4: 'npm:tailwindcss@^4.1.12'
onlyBuiltDependencies:
  - esbuild
